### ISSUE TITLE
Not working repositories

### ISSUE THREAD

**Issue by denisaq** [droidian/porting-guide#24]
When trying to compile rootfs, see following error.
2024/09/07 19:07:38 debootstrap.log | http://releases.droidian.org/snapshots/nightly/dists/rolling/InRelease:
2024/09/07 19:07:38 debootstrap.log | 2024-09-07 19:07:38 ERROR 404: Not Found.
2024/09/07 19:07:38 debootstrap.log | http://releases.droidian.org/snapshots/nightly/dists/rolling/Release:
2024/09/07 19:07:38 debootstrap.log | 2024-09-07 19:07:38 ERROR 404: Not Found.
2024/09/07 19:07:38 Action `Build Droidian` failed at stage Run, error: exit status 1

**Comment by WHO53** [comment]
nightly has been renamed to next so please use `DROIDIAN_VERSION="next"` in the docker command.
